### ISSUE TITLE
parallax

### ISSUE THREAD

**Issue by m-hejazi** [goujonpa/bagtrekkin#32]
hi everyone I'm using joomla 3.4.3 and i want to include a parallax to my website but i don't know where i need to put the code to make it work (the code is "html - javascript and css) and i need it to be in full width of page and thank you all

**Comment by m-hejazi** [comment]
any one can help me here ?

**Comment by paulgoujon** [comment]
Hi,

I've never used Joomla to create a website, I prefer to do my owns.
Anyway, I don't understand why you did open an issue for that, on github, on a non related project.

Sorry I won't be able to help you, try to contact Joomla's support.
Good luck.
